# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - main
      - feature/**
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1.x
   
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{ github.event.repository.name }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ github.event.repository.name }}
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ github.event.repository.name }}.UnitTests
