# This is a basic workflow to help you get started with Actions

name: Init Project

on: 
  create

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.ref == 'refs/heads/main'
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.0.0
      with:        
        dotnet-version: 6.0.x
    
    - name: Generate project
      run: dotnet new webapi --name ${{ github.event.repository.name }}
     
    - name: Generate test project
      run: dotnet new xunit --name ${{ github.event.repository.name }}.UnitTests
    
    - name: Git Commit Push Action
      uses: GuillaumeFalourd/git-commit-push@v1.3
